config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,  :path_prefix => 'my'
  resources :users
  scope :users do
    get 'users/new_admin', to: 'users#admin_new', :as => 'new_admin'
  end
  
  resources :branches do
    resources :schedules
  end
  resources :appointments
  
  root 'home#index'
  get '/home/about', to: 'home#about', as: 'about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/branch.rb
class Branch < ApplicationRecord
    has_many :schedules
    has_many :appointments
    
    validates_presence_of :name, message: 'El nombre no puede estar vacio' 
    validates_presence_of :address, message: 'La direccion no puede estar vacia' 
    validates_presence_of :phone_number, message: 'El telefono no puede estar vacio'
    validates_uniqueness_of :name, message: 'El nombre de la sucursal ya existe'

    def to_s
        name
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /branches or /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1 or /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches or /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branch_url(@branch), notice: "Branch was successfully created." }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branch_url(@branch), notice: "La sucursal fue correctamente actualizada." }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    #Add logic to not allow deletion if there are pending apointments in the branch copilot
    branch_appointments=@branch.appointments.filter { |appointment| appointment.pending? } 
    branch_employees= User.where(branch_id: @branch.id)
    if branch_appointments.any? || branch_employees.any?
      redirect_to branch_url(@branch), notice: "No se puede borrar la sucursal porque tiene citas pendientes o empleados asignados"
    else 
      @branch.appointments.each do |appointment|
        appointment.destroy
      end
      @branch.schedules.each do |schedule|
        schedule.destroy
      end

      @branch.destroy

      respond_to do |format|
        format.html { redirect_to branches_url, notice: "La sucursal fue correctamente borrada." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_params
      params.require(:branch).permit(:name, :address, :phone_number)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch.html.erb
<div id="<%= dom_id branch %>">
  <p>
    <strong>Name:</strong>
    <%= branch.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= branch.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= branch.phone_number %>
  </p>

</div>

app/views/branches/_form.html.erb
<%= form_with(model: branch) do |form| %>
  <% if branch.errors.any? %>
    <div style="color: red">
      <h2> Ocurrieron los siguientes errores:</h2>

      <ul>
        <% branch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Nombre", style: "display: block" %>
    <%= form.text_field :name,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Direccion", style: "display: block" %>
    <%= form.text_field :address,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Telefono", style: "display: block" %>
    <%= form.text_field :phone_number,  class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar Sucursal", class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editar sucursal</h1>

<%= render "form", branch: @branch %>


<br>

<div>
  <%= link_to "Vista detallada", @branch, class: "btn btn-info" %> |
  <%= link_to "Volver al listado", branches_path,  class: "btn btn-dark"%>
</div>

app/views/branches/index.html.erb
<h1>Sucursales</h1>
<div id="branches">
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>telefono</th>
        <th>Mostrar</th>
        <th>Horarios</th>
      </tr>
    </thead>
    <tbody>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= branch.address %></td>
          <td><%= branch.phone_number %></td>
          <td> <%= link_to "Detalles", branch, class: "btn btn-outline-info btn-sm" %> </td>

          <td> <%= link_to "Horarios", branch_schedules_path(branch), class: "btn btn-outline-info btn-sm" %>
        </tr>
         <% end %>
    </tbody>
  </table>
<div>

</div>

<% if can? :create , Branch%>
  <%= link_to "Nueva Sucursal", new_branch_path ,class: "btn btn-info" %>
<% end %>

app/views/branches/new.html.erb
<h1>Nueva sucursal</h1>

<%= render "form", branch: @branch %>

<br>

<div>
  <%= link_to "Volver al listado", branches_path,  class: "btn btn-dark" %>
</div>

app/views/branches/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    Nombre: <%= @branch.name %>
  </h1>
  <p class="lead">
    Direccion: <%= @branch.address %>  | 
    Telefono: <%= @branch.phone_number %>  
  </p>
  <br/>
<div>
  <div class='d-flex '>
    <%  if can? :update, @branch %>
      <%= link_to "Editar sucursal", edit_branch_path(@branch) ,class: "btn btn-secondary"  %> 
    <% end %>
    <% if can? :destroy, @branch %>
      <%= button_to "Borrar sucursal", @branch, method: :delete, class: "btn btn-danger"%>
    <% end %>
    <%= link_to "Volver al listado", branches_path,  class: "btn btn-dark"%>
  <div>

</div>