config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,  :path_prefix => 'my'
  resources :users
  scope :users do
    get 'users/new_admin', to: 'users#admin_new', :as => 'new_admin'
  end
  
  resources :branches do
    resources :schedules
  end
  resources :appointments
  
  root 'home#index'
  get '/home/about', to: 'home#about', as: 'about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :branch
  
  validates :open_at, :presence => true
  validates :close_at, :presence => true
  validates :day, :presence => true
  validates_presence_of :open_at, message: 'Debe especificar una hora de apertura'
  validates_presence_of :close_at, message: 'Debe especificar una hora de cierre'
  validates_presence_of :day, message: 'Debe especificar un dia'
  
  validates :day, inclusion: { in: ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"],
    message: "%{value} no es un dia valido" }
  
  validates :day, uniqueness: { scope: :branch_id,
    message: "ya existe un horario para este dia" }
  
  #validate that open hour is before close hour
  validate :open_before_close

  def open_before_close
    if open_at >= close_at
      errors.add(:open_at, "La hora de apertura debe ser antes de la hora de cierre")
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_branch 
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.where(branch_id: @branch.id)
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        @branch.schedules << @schedule
        @branch.save
        format.html { redirect_to branch_schedule_url(@branch,@schedule), notice: "El horario fue correctamente creado." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to branch_schedule_url(@branch,@schedule), notice: "El horario fue correctamente actualizado." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to branch_schedules_path, notice: "El horario fue correctamente borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:branch_id])
    end

    def set_schedule
      @schedule = Schedule.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:open_at, :close_at, :day, :branch_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_edit_form.html.erb
<%= form_with(model: schedule,url: branch_schedule_url(@branch,@schedule) ) do |form| %>
  <% if schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :open_at, style: "display: block" %>
    <%= form.time_field :open_at,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :close_at, style: "display: block" %>
    <%= form.time_field :close_at,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :day, style: "display: block" %>
    <%= form.select :day, options_for_select(["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"], schedule.day) %>
  </div>

  <div class="field form-group">
    <%= form.number_field :branch_id, value:@branch.id,type:"hidden" %> 
  </div>

  <div>
    <%= form.submit "Actualizar Horario",class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule,url: branch_schedules_path ) do |form| %>
  <% if schedule.errors.any? %>
    <div style="color: red">
      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Abre a las", style: "display: block" %>
    <%= form.time_field :open_at,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Cierra a las", style: "display: block" %>
    <%= form.time_field :close_at,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "Dia", style: "display: block" %>
    <%= form.select :day, options_for_select(["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"], schedule.day) %>
    <%=  %>
  </div>

  <div class="field form-group">
    <%= form.number_field :branch_id, value:@branch.id,type:"hidden" %> 
  </div>

  <div>
    <%= form.submit "Guardar Horario",class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div id="<%= dom_id schedule %>">
  <p>
    <strong>Open at:</strong>
    <%= schedule.open_at %>
  </p>

  <p>
    <strong>Close at:</strong>
    <%= schedule.close_at %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= schedule.day %>
  </p>

  <p>
    <strong>Branch:</strong>
    <%= schedule.branch_id %>
  </p>

</div>

app/views/schedules/edit.html.erb
<h1>Editar Horario</h1>

<%= render "edit_form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Vista detallada", branch_schedule_url(@branch,@schedule),class: "btn btn-secondary" %> |
  <%= link_to "Volver al listado", branch_schedules_path,class: "btn btn-dark" %>
</div>

app/views/schedules/index.html.erb
<h1>Horarios de la sucursal <%= @branch.name %>  </h1>

<div id="schedules">


<% if @schedules.blank? %>
  <h3> Todavia no tiene asignado horarios </h3>
<% else %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Abre a las</th>
        <th>Cierra a las</th>
        <th>Dia</th>
        <th>Mostrar</th>
      </tr>
    </thead>
    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.open_at.strftime("%H:%M:%S") %></td>
          <td><%= schedule.close_at.strftime("%H:%M:%S") %></td>
          <td><%= schedule.day %></td>
          <td> <%= link_to "Vista detallada", branch_schedule_url(@branch,schedule), class: "btn btn-outline-info btn-sm" %> </td>
        </tr>
        <% end %>
    </tbody>
  </table>
<% end %>
<% if can? :create, Schedule %>
  <%= link_to "Agregar Horarios", new_branch_schedule_path,  class: "btn btn-info" %>
<% end %>
<%= link_to "Volver al listado de sucursales", branches_path,  class: "btn btn-dark" %>
</div>

app/views/schedules/new.html.erb
<h1>Nuevo horario</h1>

<%= render "form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Volver al listado", branch_schedules_path %>
</div>

app/views/schedules/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    Dia: <%= @schedule.day %>
  </h1>
  <p class="lead">
    Abre a las: <%= @schedule.open_at.strftime("%H:%M:%S") %>  | 
    Cierra a las: <%= @schedule.close_at.strftime("%H:%M:%S") %>  
  </p>
  <br/>
<div>

<div>
  <div class='d-flex'>
  <% if can? :update, @schedule %>
    <%= link_to "Editar Horario", edit_branch_schedule_path(@branch,@schedule),class: "btn btn-secondary" %> 
  <% end %>
  <% if can? :destroy, @schedule %>
    <%= button_to "Eliminar Horario",branch_schedule_url(@branch,@schedule), method: :delete,class: "btn btn-danger" %> 
  <% end %>
  <%= link_to "Volver al listado", branch_schedules_path,class: "btn btn-dark"%>
  </div>

</div>