config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,  :path_prefix => 'my'
  resources :users
  scope :users do
    get 'users/new_admin', to: 'users#admin_new', :as => 'new_admin'
  end
  
  resources :branches do
    resources :schedules
  end
  resources :appointments
  
  root 'home#index'
  get '/home/about', to: 'home#about', as: 'about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index 
    end

    def about
        @about_me = "Este es el banco de Ruby on Rails. Una organizacion basada en Buenos Aires, Argentina. Somos un banco de primera calidad que ofrece
        una gran confianza a los clientes. Tambien contamos con sucursales en todo el pais. Para mas informacion contactese con nosotros a los siguientes contactos"
    end


    
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Banco de Ruby', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <% if can? :index,Branch %>
          <li class="nav-item">
              <%= link_to "Sucursales", branches_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if can? :index,User %>
          <li class="nav-item">
          <%= link_to "Usuarios", users_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
        <%= link_to "Turnos", appointments_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sobre nosotros", about_path, class:"nav-link" %>
        </li>
      
      
    </ul>
  
      <% if user_signed_in? %>
        <%= link_to "Editar Perfil", edit_user_path(current_user), class:"btn btn-outline-success my-2 my-sm-0" %>
        <li class="nav-item">
          <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger my-2 my-sm-0" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class:"btn btn-outline-success my-2 my-sm-0" %>
        </li>
      <% end %>
  </div>
</nav>

app/views/home/about.html.erb
<h1> Sobre nosotros </h1>
<h4 class="mt-5">
	 <%= @about_me %>
</h4>

<ul class="list-group w-100 mt-5">
    <li class="list-group-item align-items-center d-flex">
        <a class="btn text-white btn-floating m-1 me-3"
        style="background-color: hsl(330, 70%, 50%);" href="#!" role="button">
            <i class="fab fa-instagram fa-2x"></i>
        </a>
        Numero de contacto: +54 221 734 3423
    </li>
    <li class="list-group-item align-items-center d-flex">
        <a class="btn text-white btn-floating m-1 me-3"
        style="background-color: hsl(220, 44%, 41%);" href="#!" role="button">
            <i class="fab fa-facebook-f fa-2x"></i>
        </a>
        Email: RubyBank@gmail.com
    </li>
    <li class="list-group-item align-items-center d-flex">
        <a class="btn text-white btn-floating m-1 me-3"
        style="background-color: hsl(205, 81%, 63%);" href="#!" role="button">
            <i class="fab fa-twitter fa-2x"></i>
        </a>
        Sucursal principal: Reconquista 353
    </li>
</ul>

app/views/home/index.html.erb
<div id="home">
  <div clas="d-flex flex-column justify-content-center">
  <H1 class="own_golden_title"> Bienvenidos al Banco de Ruby on Rails </H1>
  <img src="https://immigrantinvest.com/wp-content/uploads/2022/03/best-banks-2021-40543452.jpg" class="img img-fluid">
  </div>
</div>