config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,  :path_prefix => 'my'
  resources :users
  scope :users do
    get 'users/new_admin', to: 'users#admin_new', :as => 'new_admin'
  end
  
  resources :branches do
    resources :schedules
  end
  resources :appointments
  
  root 'home#index'
  get '/home/about', to: 'home#about', as: 'about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client, class_name: 'User'
  belongs_to :branch, optional: false
  belongs_to :employee, class_name: 'User', optional: true

  enum status: [:pending, :canceled, :attended]

  validates_presence_of :date, message: 'La fecha no puede estar vacia' 
  validates_presence_of :motive, message: 'El motivo no puede estar vacio' 
  validates_presence_of :status, message: 'El estado no puede estar vacio' 


  #validate that the date is between branch schedule hours
  validate :date_is_between_branch_schedule_hours

  #validate that the date is not in the past
  validate :date_is_not_in_the_past
  
  def date_is_not_in_the_past
    if date.present?
      if date < Date.today
        errors.add(:date, "La fecha no puede ser en el pasado")
      end
    end
  end
  
  def date_is_between_branch_schedule_hours
    
    days=["Domingo","Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"]
    if date.present?
      if ! branch.schedules.find_by(day: days[date.wday]).nil?
        my_day_open_at=  branch.schedules.find_by(day: days[date.wday]).open_at
        my_day_close_at= branch.schedules.find_by(day: days[date.wday]).close_at
        if date.present? && branch.present?
          if date.hour < my_day_open_at.hour || date.hour > my_day_close_at.hour
            errors.add(:date, "La fecha debe estar dentro del horario de la sucursal, 
              el cual es de #{my_day_open_at.strftime("%H:%M")} a #{my_day_close_at.strftime("%H:%M")}")
          end
        end
      else
        errors.add(:date, "La sucursal no abre ese dia")
      end
    end
  end


  

  after_initialize :set_default_status, :if => :new_record?
  
  def set_default_status
    self.status ||= :pending
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /appointments or /appointments.json
  def index
    if current_user.admin?
      @actual_appointments= Appointment.all.order(date: :asc)
    elsif current_user.staff?
      @actual_appointments= Appointment.where("date >= ? AND date <= ?", DateTime.now.beginning_of_day, DateTime.now.end_of_day)
      .where(status: :pending ,branch_id: current_user.branch.id)

      @ended_appointments= Appointment.where("date >= ? AND date <= ?", DateTime.now.beginning_of_day, DateTime.now.end_of_day)
      .where(status: [:attended,:canceled]).where(branch_id: current_user.branch.id)
      @date = Date.today
    else
      @ended_appointments= Appointment.where(status: [:attended,:canceled], client_id: current_user.id)
      @actual_appointments = Appointment.where(status: :pending, client_id: current_user.id)
    end
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    appointment_data= appointment_params
    appointment_data[:client_id] = current_user.id
    appointment_data[:status] = :pending
    @appointment = Appointment.new(appointment_data)

    respond_to do |format|
      if @appointment.save
        @branch= Branch.find(@appointment.branch_id)
        @branch.appointments << @appointment
        @branch.save
        format.html { redirect_to appointment_url(@appointment), notice: "Se registro el turno satisfactoriamente" }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      #if attribute observations is empty, then redirect back to edit page
      if appointment_params[:observations].blank?
        format.html { redirect_to edit_appointment_url(@appointment), notice: "Debe ingresar una observacion sobre el turno" }
      else
        @appointment.status = :attended
        @appointment.employee_id = current_user.id
        @appointment.observations = appointment_params[:observations]
      
        if @appointment.save
          format.html { redirect_to appointments_path, notice: "Se registro la visita al turno Satisfactoriamente" }
          format.json { render :show, status: :ok, location: @appointment }
        else  
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.status = :canceled
    @appointment.save

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Se cancelo el turno satisfactoriamente" }
      format.json { head :no_content }
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through. allow branch name as a parameter
    def appointment_params
      params.require(:appointment).permit(:branch_id, :date, :motive, :status, :employee_id, :observations)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Cliente:</strong>
    <%= appointment.client.email %>
  </p>

  <p>
    <strong>Sucursal:</strong>
    <%= appointment.branch.name %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= appointment.date %>
  </p>

  <p>
    <strong>Motive:</strong>
    <%= appointment.motive %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= appointment.status %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= appointment.employee_id %>
  </p>

</div>

app/views/appointments/_edit_form.html.erb
<%= form_with(model: @appointment) do |form| %>
  <% if @appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this @appointment from being saved:</h2>

      <ul>
        <% @appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label "Observaciones", style: "display: block" %>
    <%= form.text_field :observations ,class:"form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Confirmar turno",class:"btn btn-info" %>
  </div>
<% end %>

app/views/appointments/_form.html.erb
<%= form_with(model: @appointment) do |form| %>
  <% if @appointment.errors.any? %>
    <div style="color: red">
      <h2> Ocurrieron los siguientes errores:</h2>

      <ul>
        <% @appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label "Sucursal" , style: "display: block" ,class:"form-label" %>
    <%= form.collection_select :branch_id, Branch.all, :id, :name, include_blank: false, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label "Fecha y hora", style: "display: block" %>
    <%= form.datetime_field :date, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label "Motivo", style: "display: block" %>
    <%= form.text_field :motive,class:"form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Crear turno",class:"btn btn-info" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Confirmando visita del Cliente</h1>

<%= render "edit_form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Volver al listado de turnos", appointments_path, class:"btn btn-dark" %>
</div>

app/views/appointments/index.html.erb
<div id="appointments">
  <% if current_user.user?%>
    <h2> Turnos Actuales </h2>
  <% elsif current_user.staff? %>
    <h2> Turnos pendientes del <%= @date.day %>/<%= @date.month %> de la sucursal: <%=@current_user.branch.name%> </h2>
  <% else %>
    <h2> Turnos </h2>
  <% end %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Cliente</th>
        <th>Sucursal</th>
        <th>Fecha y hora</th>
        <th>Motivo</th>
        <th>Estado</th>
        <th>Detalle</th>
        <% if current_user.staff? %>
          <th>Confirmar</th>
        <% end %>
        <% if can? :update, Appointment %>
          <th>Cancelar</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% if @actual_appointments.each do |appointment| %>
          <tr>
          <td><%= appointment.client.email %></td>
          <td><%= appointment.branch.name %></td>
          <td><%= appointment.date %></td>
          <td><%= appointment.motive %></td>
          <% if appointment.pending? %>
            <td>Pendiente</td>
          <% elsif appointment.canceled? %>
            <td>Cancelado</td>
          <% else %>
            <td>Atendido</td>
          <% end %>
          <td> <%= link_to "Vista detallada", appointment, class: "btn btn-outline-info btn-sm" %> </td>
          <% if current_user.staff? %>
            <td> <%= link_to "Confirmar visita", edit_appointment_path(appointment), class: "btn btn-outline-success btn-sm" %> </td>
          <% end %>
          <% if can? :update, Appointment %>
            <td> <%= button_to "Cancelar", appointment, method: :delete, class: "btn btn-outline-danger btn-sm"%> </td>
          <% end %>
          
        </tr>
      <% end.empty? %>
        <tr>
        <% if current_user.staff?%>
          <td colspan="8">No hay Turnos para hoy</td>
        <% elsif current_user.user? %>
          <td colspan="8">No has hecho ningun turno</td>
        <% else %>
          <td colspan="8">No hay Turnos</td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if can? :update, Appointment %>
    <h2> Turnos Finalizados </h2>
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Cliente</th>
          <th>Sucursal</th>
          <th>Fecha y hora</th>
          <th>Motivo</th>
          <th>Estado</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody>
        <% if @ended_appointments.each do |appointment| %>
            <% if appointment.canceled? %>
              <tr class="table-danger">
            <% elsif appointment.attended? %>
              <tr class="table-success">
            <% end %>
            <td><%= appointment.client.email %></td>
            <td><%= appointment.branch.name %></td>
            <td><%= appointment.date %></td>
            <td><%= appointment.motive %></td>
            <% if appointment.canceled? %>
              <td>Cancelado</td>
            <% else %>
              <td>Atendido</td>
            <% end %>
            <td> <%= link_to "Vista detallada", appointment, class: "btn btn-outline-info btn-sm" %> </td>
            
          </tr>
        <% end.empty? %>
          <tr>
          <% if current_user.staff?%>
            <td colspan="8">No hay Turnos para hoy</td>
          <% elsif current_user.user? %>
            <td colspan="8">No has hecho ningun turno</td>
          <% else %>
            <td colspan="8">No hay Turnos</td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if can? :create, Appointment %>
      <%= link_to "Crear nueva turno", new_appointment_path, class:"btn btn-info" %>
    <% end %>
  <% end %>
<div>
</div>

app/views/appointments/new.html.erb
<h1>Nuevo Turno</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Volver a mis turnos", appointments_path, class:"btn btn-secondary" %>
</div>

app/views/appointments/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    Fecha: <%= @appointment.date.strftime('%Y-%m-%d')%> 
  </h1>
  <h1 class="display-4">
    Hora: <%= @appointment.date.strftime('%H:%M') %> 
  </h1>
  <h1 class="display-4">
    Sucursal: <%= @appointment.branch.name %>
  </h1>
  
  <p class="lead">
    Cliente: <%= @appointment.client.email %>  | 
    Motivo: <%= @appointment.motive %> 
   
  </p>
  <p class="lead">
   <% if @appointment.attended?%>
      Estado: Atendido
    <% elsif @appointment.pending? %>
      Estado: Pendiente
    <% else %>
      Estado: Cancelado
    <% end %>
    | 
    <%if @appointment.attended? %>
      Comentario de la cita: <%= @appointment.observations %>
    <% end %>
  </p>
  <br/>
<div>
  <div class='d-flex '>
    <% if @appointment.pending? %>
      <%= button_to "Cancelar cita", @appointment, method: :delete, class: "btn btn-danger"%>
    <% end %>
    <%= link_to "Volver al listado", appointments_path,  class: "btn btn-primary" %>
  <div>

</div>